# Generated by Django 5.2.6 on 2025-09-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entities/'),
        ),
    ]
