# Generated by Django 5.2.6 on 2025-09-15 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_avatar_alter_entity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='object_class',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Euclid', 'Euclid'), ('Keter', 'Keter'), ('Thaumiel', 'Thaumiel'), ('Archon', 'Archon')], default='Euclid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='clearance_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Clearance level must be between 1 (lowest) and 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Class-D Personnel', 'Class-D Personnel'), ('Researcher', 'Researcher'), ('Security Guard', 'Security Guard'), ('O5 Council', 'O5 Council'), ('Site Director', 'Site Director'), ('Medical Staff', 'Medical Staff'), ('Technician', 'Technician')], default='Class-D Personnel', max_length=50),
        ),
    ]
